BOARD_SIZE = 640
SQUARE_SIZE = BOARD_SIZE // 8
SIDEBAR_WIDTH = 200
LEFTBAR_WIDTH = 60
TOPBAR_HEIGHT = 60
BOTTOMBAR_HEIGHT = 40

WIDTH = LEFTBAR_WIDTH + BOARD_SIZE + SIDEBAR_WIDTH
HEIGHT = TOPBAR_HEIGHT + BOARD_SIZE + BOTTOMBAR_HEIGHT
